version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.10.18-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq/
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_PORT_WEB}:${RABBITMQ_PORT_WEB}
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=${RABBITMQ_DISK_FREE_LIMIT}
