CREATE TABLE public.roles (
  "id" SERIAL NOT NULL CONSTRAINT "PK_2_1" PRIMARY KEY,
  "name" CHARACTER VARYING UNIQUE NOT NULL
);

CREATE TABLE public.rules (
  "id" SERIAL NOT NULL CONSTRAINT "PK_2_2" PRIMARY KEY,
  "method" CHARACTER VARYING UNIQUE NOT NULL,
  "def" CHARACTER VARYING UNIQUE NOT NULL
);

CREATE TABLE public.role_rules (
  "id" SERIAL NOT NULL CONSTRAINT "PK_2_3" PRIMARY KEY,
  "role_id" INTEGER NOT NULL CONSTRAINT "fk_2_1" REFERENCES public.roles,
  "rule_id" INTEGER NOT NULL CONSTRAINT "fk_2_2" REFERENCES public.rules
);
